### PR TITLE
Allow `"noEmitOnError": false`

### PR DESCRIPTION
**Pull request by wojpawlik**
@dsherret did I handle diagnostics properly? What are "declaration emit diagnostics", ie. what kinds of errors can they contain? Related: https://github.com/dsherret/ts-morph/issues/384

### CODE REVIEW

**Comment by dsherret** [comment]
@wojpawlik what are you trying to do?

**Comment by wojpawlik** [comment]
I'm trying to correctly report all errors, with or without `noEmitOnError`, did I get it right?

`project.getPreEmitDiagnostics().concat(result.getDiagnostics())` reports errors twice with `noEmitOnError: true`,
just `result.getDiagnostics()` swallows errors with `noEmitOnError: false`.

**Comment by dsherret** [comment]
@wojpawlik I think what would be best is to check for pre-emit diagnostics before emitting, then emit, then check `result.getDiagnostics()`.

**Comment by dsherret** [comment]
@wojpawlik `getPreEmitDiagnostics()` does not transform the code and more diagnostics may occur at that time.

See this function in the compiler and how it calls `addDiagnostic`: https://github.com/microsoft/TypeScript/blob/38da7c600c83e7b31193a62495239a0fe478cb67/src/compiler/transformers/declarations.ts#L52

**Comment by wojpawlik** [comment]
Thank you. Last question: why `result.getDiagnostic()` does not contain pre-emit diagnostics without `noEmitOnError`?

**Comment by dsherret** [comment]
@wojpawlik oh, I did not know it would do that or even check the pre-emit diagnostics within `program.emit()`. You can see the code here: https://github.com/microsoft/TypeScript/blob/f6d425e1e3fb4f52a2935a8d7f7c2133ccbcb63f/src/compiler/program.ts#L3847

**Comment by wojpawlik** [comment]
@dsherret what code triggers a declaration diagnostic? I wanna test and perhaps refine my diagnostic handling.

**Pull request closed without merging**
