### PR TITLE
Replace `fixMissingImports()` with `"shim"` option

### LINKED ISSUE #4: Drop `fixMissingImports`
## Problem description

Using `sourceFile.fixMissingImports();` is opaque. It is not clear which dependencies are imported. Also, the imported things are not necessarily stable, they could suddenly change as I add new source files. It is not clear which symbol will be imported on clashing names. If symbols are re-exported (e.g. in `mod.ts`, it is not clear which location will be picked, original declaration or re-export.

## Desired solution

Let users specify a file with the explicit dependencies to be used that are expected to be missing, either via a program argument or just by using a default hard-coded file name for now. Then add a `import * from './<filename>.ts'` as a first line to every source file.

It may be possible to explicitly import all members from that given file, and then let <https://ts-morph.com/details/source-files#organizing-imports> remove the unused things. This has a similar effect as fixing all missing imports, but it is explicit and there are no doubts about where things are coming from. Being explicit is a good thing, and so is reproducibility.

### PR DESCRIPTION
**Pull request by wojpawlik**
Fixes #4. Try it out: `$ deno run --unstable --allow-read --allow-write https://raw.githubusercontent.com/wojpawlik/deno2node/shim/src/cli.ts <tsConfigFilePath>`

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Is is supposed to compile this project's `main` branch?

```bash
~/git/deno2node$ deno run --unstable --allow-read --allow-write https://raw.githubusercontent.com/wojpawlik/deno2node/shim/src/cli.ts src/tsconfig.json 
src/cli.ts:4:5 - error TS2304: Cannot find name 'Deno'.

4 if (Deno.args.length !== 1 || Deno.args[0].startsWith("-")) {
      ~~~~
src/cli.ts:4:31 - error TS2304: Cannot find name 'Deno'.

4 if (Deno.args.length !== 1 || Deno.args[0].startsWith("-")) {
                                ~~~~
src/cli.ts:6:3 - error TS2304: Cannot find name 'Deno'.

6   Deno.exit(2);
    ~~~~
src/cli.ts:9:23 - error TS2304: Cannot find name 'Deno'.

9 emitAndExit(deno2node(Deno.args[0]));
                        ~~~~
src/emit_and_exit.ts:6:33 - error TS2322: Type 'any' is not assignable to type 'never'.

6   if (diagnostics.length === 0) return Deno.exit(0);
                                  ~~~~~~~~~~~~~~~~~~~~
src/emit_and_exit.ts:6:40 - error TS2304: Cannot find name 'Deno'.

6   if (diagnostics.length === 0) return Deno.exit(0);
                                         ~~~~
src/emit_and_exit.ts:9:3 - error TS2322: Type 'any' is not assignable to type 'never'.

9   return Deno.exit(1);
    ~~~~~~~~~~~~~~~~~~~~
src/emit_and_exit.ts:9:10 - error TS2304: Cannot find name 'Deno'.

9   return Deno.exit(1);
           ~~~~

Found 8 errors.
```

**Comment by wojpawlik** [comment]
No, it's marked `[breaking]` for a reason :)

CI passed, but if you wanna build it anyway:

```sh
$ git switch shim
$ npm run prepare
```

I'd rather you tried using it on `grammy`.

**Comment by KnorpelSenf** [comment]
Works smoothly on grammY runner :rocket:

**Review by KnorpelSenf — APPROVED** [review]
I migrated grammY runner to use this commit for builds. Looking forward to seeing a stable version that includes this so I can rely on the tool when publishing a stable version myself, and when migrating grammY.

**Pull request merged**
