### PR TITLE
Upgrade to TypeScript 4.5

### PR DESCRIPTION
**Pull request by KnorpelSenf**
This makes TS 4.5 available.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Why in draft state?

**Comment by wojpawlik** [comment]
Major ts-morph releases upgrade TypeScript version. There's no Deno release with TS 4.5 yet.

**Comment by KnorpelSenf** [comment]
Related: https://github.com/denoland/dnt/pull/44

**Comment by wojpawlik** [comment]
https://github.com/colinhacks/zod/pull/648, https://github.com/wojpawlik/deno2node/commit/aef011a6b0a4441a1a05c9258fa5838934cccf46#diff-1f6f06ffdff13bc5394df222422f6364a7abb96d569dbc073300d9e26bcafa04

**Review by wojpawlik — APPROVED** [review]

**Pull request merged**
